INSERT INTO `ngms`.`excels` (`id`, `busiType`, `name`, `state`) VALUES ('61', 'operation', '运维记录导出表', '1');


INSERT INTO `ngms`.`excel_parts` (`id`, `excel_id`, `sheet_sql`, `head_sql`, `data_sql`, `template`, `sort`, `state`) VALUES ('60', '61', 'select id,name from sites t where t.state = 1', NULL, 'select t.id,t.siteid,t.faulttype,t.subtype,t.subtypename,t.desc,t.procedure,t.changedev,t.createtime,t.creator,t.company,t.state,\r\n(select group_concat(name) from dict where group_code = \'OPERATION.DEVICE\' and find_in_set(code, t.changedev)) changedevname, \r\nt.occurdtime ,t.solvetime, \r\n(case t.faulttype when \'1\' then \'离线\' else \'告警\' end) faulttypename,s.name from tank_operation t \r\nleft join sites s on t.siteid = s.id \r\nwhere t.state = 1 and t.siteid=#id #filter\r\n order by t.id asc ', '26', '1', '1');


INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('953', '26', '运维记录', NULL, NULL, '0', '0', 'Y', '0', '7', '', '', NULL, '', NULL, NULL, '', '');
INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('954', '26', '站点名称', '6000', NULL, '1', '0', 'N', NULL, NULL, '', '', NULL, '', NULL, NULL, '', 'name');
INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('955', '26', '发生时间', '6000', NULL, '1', '1', 'N', NULL, NULL, '', '', NULL, '', NULL, NULL, '', 'occurdtime');
INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('956', '26', '解决时间', '6000', NULL, '1', '2', 'N', NULL, NULL, '', '', NULL, '', NULL, NULL, '', 'solvetime');
INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('957', '26', '故障类型', '4500', NULL, '1', '3', 'N', NULL, NULL, '', '', NULL, '', NULL, NULL, '', 'changedevname');
INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('958', '26', '故障小类', '4500', NULL, '1', '4', 'N', NULL, NULL, '', '', NULL, '', NULL, NULL, '', 'subtype');
INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('959', '26', '更换设备', '4500', NULL, '1', '5', 'N', NULL, NULL, '', '', NULL, '', NULL, NULL, '', 'changedevname');
INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('960', '26', '设备描述', '6500', NULL, '1', '6', 'N', NULL, NULL, '', '', NULL, '', NULL, NULL, '', 'desc');
INSERT INTO `ngms`.`excel_cells` (`id`, `template`, `cellname`, `width`, `height`, `startRow`, `startColumn`, `isMerge`, `endRow`, `endColumn`, `border`, `autoWrap`, `bgColor`, `fontName`, `fontColor`, `fontSize`, `fontBold`, `property`) VALUES ('961', '26', '处理过程', '8000', NULL, '1', '7', 'N', NULL, NULL, '', '', NULL, '', NULL, NULL, '', 'procedure');
